export default {
  light: {
    text: '#18181B',
    textSecondary: '#71717A',
    background: '#FFFFFF',
    card: '#FAFAFA',
    border: '#E4E4E7',
    tint: '#18181B',
    tabIconDefault: '#A1A1AA',
    tabIconSelected: '#18181B',
    surface: '#F9FAFB',
    surfaceElevated: '#FFFFFF',
    surfaceMuted: '#F3F4F6',
  },
  dark: {
    text: '#FAFAFA',
    textSecondary: '#A1A1AA',
    background: '#0A0A0A',
    card: '#18181B',
    border: '#27272A',
    tint: '#FAFAFA',
    tabIconDefault: '#52525B',
    tabIconSelected: '#FAFAFA',
    surface: '#1A1A1A',
    surfaceElevated: '#1A1A1A',
    surfaceMuted: '#2A2A2A',
  },
};
